
export const categories = [
    {
        id: 1,
        name: "เสื้อผ้า",
        slug: "clothing",
    },
    {
        id: 2,
        name: "อุปกรณ์อิเล็กทรอนิกส์",
        slug: "electronics",
    },
    {
        id: 3,
        name: "อุปกรณ์สำนักงาน",
        slug: "office",
    },
];
export const products = [
    {
        id: 1,
        name: "เสื้อยืดคอกลมสีขาว",
        categoryId: 1,
        category: "เสื้อผ้า",
        description: "เสื้อยืดผ้าคอตตอนเนื้อนุ่ม ใส่สบาย ระบายอากาศได้ดี",
        price: 250,
        originalPrice: 299,
        stock: 12,
        image_url: "/images/white-t-shirt.webp",
        rating: 4.5,
        reviews: 45,
    },
    {
        id: 2,
        name: "กางเกงยีนส์เอวสูง",
        categoryId: 1,
        category: "เสื้อผ้า",
        description: "กางเกงยีนส์ทรงสวย เนื้อผ้ายืดหยุ่น พร้อมกระเป๋าทั้งสองข้าง",
        price: 750,
        originalPrice: 890,
        stock: 7,
        image_url: "/images/jeans.webp",
        rating: 4.3,
        reviews: 28,
    },
    {
        id: 3,
        name: "แจ็คเก็ตยีนส์",
        categoryId: 1,
        category: "เสื้อผ้า",
        description:
            "แจ็คเก็ตทรงคลาสสิก ดีไซน์เรียบง่าย เหมาะกับการแต่งตัวหลากหลายสไตล์",
        price: 1200,
        originalPrice: 1500,
        stock: 5,
        image_url: "/images/white-t-shirt.webp",
        rating: 4.7,
        reviews: 32,
    },
    {
        id: 4,
        name: "ชุดเดรสลายดอก",
        categoryId: 1,
        category: "เสื้อผ้า",
        description:
            "ชุดเดรสผ้าชีฟองบางเบา ลายดอกไม้สวยงาม ใส่สบายเหมาะกับอากาศร้อน",
        price: 890,
        originalPrice: 990,
        stock: 9,
        image_url: "/images/dress.webp",
        rating: 4.4,
        reviews: 56,
    },
    {
        id: 5,
        name: "สมาร์ทโฟน X100",
        categoryId: 2,
        category: "อุปกรณ์อิเล็กทรอนิกส์",
        description: "สมาร์ทโฟนหน้าจอ 6.5 นิ้ว กล้อง 3 ตัว รองรับ 5G แบตอึด",
        price: 12000,
        originalPrice: 15900,
        stock: 15,
        image_url: "/images/X100.webp",
        rating: 4.8,
        reviews: 122,
    },
    {
        id: 6,
        name: "แท็บเล็ต A10",
        categoryId: 2,
        category: "อุปกรณ์อิเล็กทรอนิกส์",
        description:
            "แท็บเล็ตหน้าจอ 10 นิ้ว ความละเอียดสูง เหมาะสำหรับความบันเทิงและงานเอกสาร",
        price: 9900,
        originalPrice: 11900,
        stock: 8,
        image_url: "/images/tablet.webp",
        rating: 4.6,
        reviews: 89,
    },
    {
        id: 7,
        name: "หูฟังไร้สาย Noise-Canceling",
        categoryId: 2,
        category: "อุปกรณ์อิเล็กทรอนิกส์",
        description:
            "หูฟังไร้สายตัดเสียงรบกวน มีไมโครโฟนในตัว เชื่อมต่อผ่าน Bluetooth",
        price: 3200,
        originalPrice: 3990,
        stock: 20,
        image_url: "/images/headphone.webp",
        rating: 4.5,
        reviews: 167,
    },
    {
        id: 8,
        name: "ปากกาลูกลื่นเซ็ต 5 ด้าม",
        categoryId: 3,
        category: "อุปกรณ์สำนักงาน",
        description: "ปากกาลูกลื่นสีดำ เขียนลื่น หมึกไม่เลอะง่าย จับถนัดมือ",
        price: 50,
        originalPrice: 75,
        stock: 50,
        image_url: "/images/pen_set.webp",
        rating: 4.2,
        reviews: 234,
    },
    {
        id: 9,
        name: "สมุดโน้ตปกแข็ง A5",
        categoryId: 3,
        category: "อุปกรณ์สำนักงาน",
        description: "สมุดโน้ตขนาด A5 ปกแข็ง ทนทาน เหมาะสำหรับจดบันทึกทุกประเภท",
        price: 120,
        originalPrice: 150,
        stock: 30,
        image_url: "/images/hardcover_notebook.webp",
        rating: 4.4,
        reviews: 178,
    },
    {
        id: 10,
        name: "เก้าอี้สำนักงานปรับระดับ",
        categoryId: 3,
        category: "อุปกรณ์สำนักงาน",
        description:
            "เก้าอี้สำนักงานนั่งสบาย ปรับระดับสูง-ต่ำได้ พร้อมพนักพิงหลังและล้อเลื่อน",
        price: 2990,
        originalPrice: 3590,
        stock: 4,
        image_url: "/images/office_chair.webp",
        rating: 4.6,
        reviews: 92,
    },
];